### ISSUE TITLE
pubspec.yaml points to flutter_clock_helper that is not in the repo

### ISSUE THREAD

**Issue by tomaszpolanski** [miickel/flutter_particle_clock#1]
Hey,
this dependency does not exist in the repo:
```
  flutter_clock_helper:
    path: ../flutter_clock_helper
```
Can it be added somewhere?

**Comment by johnhouston00** [comment]
https://github.com/flutter/flutter_clock , there is a set of helper packages provided by flutter.

**Comment by tomaszpolanski** [comment]
Thanks @johnhouston00, I will create a PR fixing this if the author will accept it
