### ISSUE TITLE
Brother can you please do a web/destop/app demo for us why wont u reply?

### ISSUE THREAD

**Issue by fisforfaheem** [miickel/flutter_particle_clock#11]
we want

**Comment by miickel** [comment]
I unfortunately don't have time to make this into a web/desktop version. Why don't you do it, instead of opening all these issues asking others to do it?

It's all open source and anyone can do it. I welcome a pull request. But please stop opening these issues, there are already several duplicates.

**Comment by fisforfaheem** [comment]
Thanks for the clarification, I thought that...If you made this into an APK FILE. I would have used it as a screensaver...or something for my fire HD tablet!!

Thanks, I will surely try myself, I tried last year but failed!! that's why I was asking! anyway! U are busy, We don't mind...If I could  run it! I will put it on netlify! and give a link!

**Comment by Uuttssaavv** [comment]
@fisforfaheem  I just tested it and now it works fine on web

**Comment by fisforfaheem** [comment]
yes al so committed and upgraded it to work on new flutter version
