### ISSUE TITLE
Dear DEV, Please release the app in windows pc too and utilize flutter

### ISSUE THREAD

**Issue by fisforfaheem** [miickel/flutter_particle_clock#5]
It's time to show how much talented u are

**Comment by stuartmorgan-g** [comment]
You can already run it using [the Flutter for Windows technical preview](https://github.com/flutter/flutter/wiki/Desktop-shells), following the usual instructions for running an existing project:
- [Enable the Windows](https://github.com/flutter/flutter/wiki/Desktop-shells#tooling) preview if you haven't already.
- Update [this line](https://github.com/miickel/flutter_particle_clock/blob/master/lib/main.dart#L13) to [apply to Windows](https://github.com/flutter/flutter/wiki/Desktop-shells#target-platform-override).
- [Copy in a Windows runner](https://github.com/google/flutter-desktop-embedding/tree/master/example#adapting-for-another-project), per the instructions [here](https://github.com/flutter/flutter/wiki/Desktop-shells#create).

**Comment by fisforfaheem** [comment]
I am not much of a geek or a good programmer that's why i sinstited to get a .exe file to check it on my pc. Please help me
